apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: waves-of-the-fallen
build:
  local:
    push: false
  artifacts:
    - image: kaprele/waves-of-the-fallen_backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "."
    - image: kaprele/waves-of-the-fallen_game
      context: Game
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*

profiles:
  - name: prod
    build:
      local:
        push: true
      tagPolicy:
        dateTime: { }
      artifacts:
        - image: docker.io/kaprele/waves-of-the-fallen_backend
          context: backend
          docker:
            dockerfile: Dockerfile
        - image: kaprele/waves-of-the-fallen_game
          context: Game
          docker:
            dockerfile: Dockerfile