apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: waves-of-the-fallen
build:
  local:
    push: false
  artifacts:
    - image: kaprele/waves-of-the-fallen_backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: kaprele/k8s-hello-pod
      context: hello-pod
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './*.js'
            dest: .
manifests:
  rawYaml:
    - k8s/*

profiles:
  - name: prod
    build:
      local:
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.VERSION}}"
      artifacts:
        - image: docker.io/kaprele/waves-of-the-fallen_backend
          context: backend
          docker:
            dockerfile: Dockerfile
