### GET request to example server
GET http://localhost/api/v1/healthz
###

POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@mail.com",
  "username": "newUser",
  "password": "newPassword"
}
###

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "newPassword"
}

###

GET http://localhost/pgadmin

###

POST http://localhost:3000/api/v1/protected/getAllUnlockedCharacters
Content-Type: application/json

{
  "user_id": "D465D2FD-092C-40A6-945D-E29E99FA524A"
}

###

POST http://localhost:3000/api/v1/protected/character/unlock
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMyYTkxMWVkLTgzYjktNDIxMS1hNzlkLTg3ODViYzViMmY0NiIsImlhdCI6MTc0NjU2OTk5MiwiZXhwIjoxNzQ3MTc0NzkyfQ.zWnY1K-EhKTat8IMLIwZ4ROnbT3Ht2vIoOskndr6GH0

{
  "character_id": 1
}