apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: waves-of-the-fallen
subjects:
  - kind: ServiceAccount
    name: default
    namespace: waves-of-the-fallen
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
