apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: waves-of-the-fallen
  name: pod-creator
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "list", "delete", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update"]

