apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_DATABASE: "backend_db"
  DB_URL: "postgresql://postgres:postgres@db:5432/backend_db?schema=public"


  # this is the sample.db-secret.yaml file for dev on local machine, similar to a .env
  # copy the contents of this file into the `root/k8s/db-secret.yaml file